package test;
// Generated Jan 3, 2018 5:47:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Command generated by hbm2java
 */
public class Command  implements java.io.Serializable {


     private int id;
     private Date timestamp;
     private Session session;
     private String commandType;

    public Command() {
    }

    public Command(int id, Session session, String commandType) {
       this.id = id;
       this.session = session;
       this.commandType = commandType;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public Session getSession() {
        return this.session;
    }
    
    public void setSession(Session session) {
        this.session = session;
    }
    public String getCommandType() {
        return this.commandType;
    }
    
    public void setCommandType(String commandType) {
        this.commandType = commandType;
    }




}


