package test;
// Generated Jan 3, 2018 5:47:37 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Session generated by hbm2java
 */
public class Session  implements java.io.Serializable {


     private int id;
     private User user;
     private Date startTime;
     private Date endTime;
     private Set<Command> commands = new HashSet<Command>(0);

    public Session() {
    }

	
    public Session(int id, User user, Date startTime) {
        this.id = id;
        this.user = user;
        this.startTime = startTime;
    }
    public Session(int id, User user, Date startTime, Date endTime, Set<Command> commands) {
       this.id = id;
       this.user = user;
       this.startTime = startTime;
       this.endTime = endTime;
       this.commands = commands;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public Set<Command> getCommands() {
        return this.commands;
    }
    
    public void setCommands(Set<Command> commands) {
        this.commands = commands;
    }




}


