package test;
// Generated Jan 3, 2018 5:47:37 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String name;
     private String password;
     private Date createdTime;
     private String type;
     private Set<Session> sessions = new HashSet<Session>(0);

    public User() {
    }

	
    public User(int id, String name, String password, Date createdTime, String type) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.createdTime = createdTime;
        this.type = type;
    }
    public User(int id, String name, String password, Date createdTime, String type, Set<Session> sessions) {
       this.id = id;
       this.name = name;
       this.password = password;
       this.createdTime = createdTime;
       this.type = type;
       this.sessions = sessions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    public Set<Session> getSessions() {
        return this.sessions;
    }
    
    public void setSessions(Set<Session> sessions) {
        this.sessions = sessions;
    }




}


